# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 70b14e14f35117907773f943b45e2477411d2954ff633a60d205684e588de7395a2bd68fe4d40d21efcb010d93894d7705eac2d5c0f4b68266b3812cb7060f22

test:
  secret_key_base: b934755debdce53844f17c9a968cc50ed09d80e505094621c1eaf69ad7e6b2cd688fa6dee76e785b4376ada80b9ee6bc3e143c489dd6ccb252005b010c41bdbf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
